#!/usr/bin/env python3
"""
setup_docs.py — Idempotent, pathlib-based scaffolder for the Enterprise RAG
Architecture & System Analysis Package.

Creates a versioned documentation tree under ``docs/`` and seeds each
Markdown deliverable with pre-populated YAML front-matter metadata plus a
title block, so downstream authors start from a consistent, reviewable
skeleton.

Design properties
-----------------
* **Idempotent** — re-running never overwrites or corrupts existing files
  (existing files are skipped and logged as such).
* **Atomic writes** — content is written to a temporary file in the same
  directory, fsync'd, then ``os.replace``'d onto the target. A crash
  mid-write can never leave a half-written document.
* **Robust error handling** — ``try/except`` around every filesystem
  operation, with specific exception handling and non-zero exit codes.
* **Structured logging** — timestamped stdout logs with configurable
  verbosity (``--verbose``).

Usage
-----
    python3 scripts/setup_docs.py [--root PATH] [--force] [--verbose]

Exit codes
----------
    0    success (all files present, created, or safely skipped)
    1    fatal error (filesystem / permission / unexpected failure)
    130  interrupted by user (SIGINT)

Requires Python 3.9+. Standard library only — no third-party dependencies.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

LOG = logging.getLogger("rag.docs")

__version__ = "1.0.0"

DEFAULT_ROOT = Path("docs")
ASSETS_DIRNAME = "assets"

# ---------------------------------------------------------------------------
# Pre-populated Markdown seed content (front matter + title + seed note)
# ---------------------------------------------------------------------------

_FRONT_MATTER_01 = """\
---
title: "Requirement Analysis - Enterprise RAG"
artifact_id: RAG-REQ-001
package_part: "2 of 4"
domain: Financial Services
cloud_target: "AWS (us-east-1 primary, eu-west-1 for EU data residency)"
compliance: [SOC 2 Type II, GDPR]
scale_targets: ["10M+ documents", "P95 < 800 ms", "99.9% monthly availability"]
status: draft
version: 0.1.0
owner: Platform Architecture
---

# Part 2 - Requirement Analysis (Scope, Actors, FRs, NFRs, Constraints)
"""

_FRONT_MATTER_02 = """\
---
title: "Data Flow Diagrams - Enterprise RAG"
artifact_id: RAG-DFD-001
package_part: "3 of 4"
notation: "Mermaid.js (flowchart)"
diagrams: ["Level 0 Context Diagram", "Level 1 Decomposed Data Flow"]
domain: Financial Services
status: draft
version: 0.1.0
owner: Platform Architecture
---

# Part 3 - Data Flow Diagrams (DFD Level 0 & Level 1, Mermaid.js)
"""

_FRONT_MATTER_03 = """\
---
title: "Spiral SDLC Plan - Enterprise RAG"
artifact_id: RAG-SDLC-001
package_part: "4 of 4"
lifecycle_model: "Spiral (Boehm)"
loops: 3
quadrants_per_loop: 4
loop_scope:
  - "Loop 1: Naive RAG Proof-of-Concept"
  - "Loop 2: Advanced RAG Optimization"
  - "Loop 3: Production Enterprise RAG"
status: draft
version: 0.1.0
owner: Platform Architecture
---

# Part 4 - Spiral SDLC Plan (3 Loops x 4 Quadrants)
"""

_SEED_NOTE = """\
> **Seed file** - generated by ``scripts/setup_docs.py``.
> Replace this placeholder body with the full deliverable content.
"""

TEMPLATES: Dict[str, str] = {
    "01_requirement_analysis.md": _FRONT_MATTER_01 + "\n" + _SEED_NOTE,
    "02_data_flow_diagrams.md": _FRONT_MATTER_02 + "\n" + _SEED_NOTE,
    "03_spiral_sdlc_plan.md": _FRONT_MATTER_03 + "\n" + _SEED_NOTE,
}


# ---------------------------------------------------------------------------
# Low-level helpers
# ---------------------------------------------------------------------------

def ensure_directory(directory: Path) -> None:
    """Create *directory* (and all missing parents) if it does not exist.

    Raises:
        RuntimeError: if the directory cannot be created (permissions,
            filesystem failure, or a non-directory path blocking the way).
    """
    try:
        directory.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise RuntimeError(
            f"Unable to create directory '{directory}': {exc}"
        ) from exc
    if not directory.is_dir():
        raise RuntimeError(f"Path '{directory}' exists but is not a directory")
    LOG.debug("Directory ready: %s", directory)


def write_atomic(target: Path, content: str) -> None:
    """Write *content* to *target* atomically.

    The content is first written to a temporary file in the *same*
    directory (guaranteeing the same filesystem for the final rename),
    flushed and fsync'd, then moved into place with ``os.replace``, which
    is atomic on POSIX. On any failure the temporary file is cleaned up
    and the original exception is re-raised.

    Raises:
        OSError: on any filesystem failure.
    """
    directory = target.parent
    fd: int
    tmp_path: str
    fd, tmp_path = tempfile.mkstemp(
        dir=str(directory),
        prefix=f".{target.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, target)
    except BaseException:
        # Remove the half-written temp file, then propagate the original
        # exception unchanged.
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def create_document(target: Path, content: str, force: bool = False) -> str:
    """Create *target* with *content*, respecting idempotency.

    Args:
        target: Destination file path.
        content: Full file content to write.
        force: If True, overwrite an existing file; if False, skip it.

    Returns:
        One of ``"created"``, ``"rewritten"``, or ``"skipped"``.

    Raises:
        OSError: on any filesystem failure.
    """
    exists = target.exists()
    if exists and not force:
        LOG.warning("Exists - leaving untouched: %s", target)
        return "skipped"
    if exists and force:
        LOG.info("Force reseed requested - overwriting: %s", target)
        action = "rewritten"
    else:
        action = "created"
    write_atomic(target, content)
    LOG.info("%s: %s", "Rewrote" if action == "rewritten" else "Created", target)
    return action


# ---------------------------------------------------------------------------
# High-level orchestration
# ---------------------------------------------------------------------------

def build_doc_tree(root: Path, force: bool = False) -> Tuple[int, int, int]:
    """Build the documentation tree under *root*.

    Layout produced::

        <root>/
        ├── 01_requirement_analysis.md
        ├── 02_data_flow_diagrams.md
        ├── 03_spiral_sdlc_plan.md
        └── assets/
            └── .gitkeep

    Args:
        root: Root directory of the documentation tree.
        force: Overwrite existing seed files when True.

    Returns:
        ``(created, rewritten, skipped)`` counts.

    Raises:
        RuntimeError: on unrecoverable directory creation failure.
        OSError: on unrecoverable file write failure.
    """
    counts: Dict[str, int] = {"created": 0, "rewritten": 0, "skipped": 0}

    LOG.info("Building documentation tree under: %s", root)
    ensure_directory(root)
    assets = root / ASSETS_DIRNAME
    ensure_directory(assets)

    gitkeep = assets / ".gitkeep"
    if not gitkeep.exists():
        write_atomic(gitkeep, "")
        LOG.info("Created: %s", gitkeep)

    for filename, content in TEMPLATES.items():
        action = create_document(root / filename, content, force=force)
        counts[action] += 1

    return counts["created"], counts["rewritten"], counts["skipped"]


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def configure_logging(verbose: bool) -> None:
    """Configure root logging to stdout."""
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        stream=sys.stdout,
    )


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        prog="setup_docs.py",
        description=(
            "Idempotently scaffold the Enterprise RAG documentation tree "
            "(docs/ with pre-populated Markdown metadata headers)."
        ),
    )
    parser.add_argument(
        "--root",
        type=str,
        default=str(DEFAULT_ROOT),
        help=f"Root directory for the doc tree (default: {DEFAULT_ROOT})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing seed files (default: skip them)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable debug-level logging",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {__version__}",
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    """CLI entry point. Returns a process exit code."""
    args = parse_args(argv)
    configure_logging(args.verbose)
    root = Path(args.root).expanduser().resolve()

    try:
        created, rewritten, skipped = build_doc_tree(root, force=args.force)
    except KeyboardInterrupt:
        LOG.error("Aborted by user.")
        return 130
    except (RuntimeError, OSError) as exc:
        LOG.error("Fatal error: %s", exc)
        return 1

    LOG.info(
        "Done. created=%d rewritten=%d skipped=%d (root=%s)",
        created,
        rewritten,
        skipped,
        root,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
